apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ $.Chart.Name }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ $.Chart.Name }}:latest
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.imageSource.name }}:{{ .Values.imageSource.tag }}
    type: Source